### ISSUE TITLE
Anti Recall 

### ISSUE THREAD

**Issue by rabe33h** [Xposed-Modules-Repo/nep.timeline.re_telegram#1]
Thank you for this greating Module..
When someone deletes the entire conversation, not a single message, all messages are deleted.

![IMG_20230726_220712](https://github.com/Xposed-Modules-Repo/nep.timeline.re_telegram/assets/73466503/7b6fce74-2eba-40ec-964c-4edfe69ef5aa)

**Comment by Nep-Timeline** [comment]
The issue raised here will not be accepted.
Please go to https://github.com/Nep-Timeline/Re-Telegram/issues Create your issue
